### ISSUE TITLE
Migrate Unit Tests to tests/unit_tests

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#109]
The following modules in `tests/legacy` appear to be unit tests that do not interact with the filesystem:
- `run_trim_test.py`
- `test_build_finders_table.py`
  Copy those modules to `tests/unit_tests` and update the imports so that they pass.

**Comment by ktfhale** [comment]
I've moved these two files into `tests/unit_tests`. I've modified their import statements, and the import statements of some of the files they call, to be of the format `mtpipeline.<folder>.<filename>`. 

Travis continues to behave strangely, with `Connections reset by peer` errors appearing on different packages each time. Locally, on my machine, the nosetests all appear to pass. I'm submitting a pull request, and hoping that the Travis build _that_ creates will thread the gauntlet.
