### ISSUE TITLE
Testing cosmicx on WFC3 and ACS data

### ISSUE THREAD

**Issue by ktfhale** [STScI-Citizen-Science/MTPipeline#111]
We need to figure out what the proper settings are for optimal cosmic ray rejection on WFC3 and ACS data. I'll start by using the WFPC2 settings as a baseline.

Judging what works best is probably going to by eye. I can diff the cleaned images with the original, and compare those, but, as it was when evaluating cosmics vs cosmicx, it's still going to be pretty subjective.

**Comment by walyssonBarbosa** [comment]
Tried to assign values to `sigclip` parameter from `0.5` to `10.0` but the cosmic ray rejected outputs for `/astro/mtpipeline/archive/wfc3/13067_JUPITER/ic3g04snq_flt.fits` present the same cosmic rays as the original `fits` file.

**Comment by acviana** [comment]
This is the commit where my intern last summer changed some the values `cosmics.py` was using. 

https://github.com/STScI-Citizen-Science/MTPipeline/commit/57b028bd78294a46ea2a943cdcd4138961fb3322

Granted that `cosmicx.py` is a different implementation, but it is still the same algorithm so I think you should focus your work on the two parameters he changed.

**Comment by ktfhale** [comment]
The two parameters changed were `sigclip` and `readnoise`. I've experimented with increasing the latter from 1, the value it was changed to, but it in general doing so just seemed to make the quality of the rejection marginally worse. I've focused primarily on varying `sigclip`, which has dramatic results.

To determine the HRC parameters, I've been working on this image of Mars:

![screen shot 2014-07-09 at 3 42 18 pm](https://cloud.githubusercontent.com/assets/7748162/3530316/4a0ca8fc-07a3-11e4-9d40-a99ea18a4815.png)

from the MARS-2005-ACS dataset. It looks particularly fuzzy because DS9's set to use the min max/histogram scale. I'm doing this because it seems to be the best way to spot cosmics. If you use a more prosiac scale, like zcale / linear, you just see

![screen shot 2014-07-09 at 3 59 28 pm](https://cloud.githubusercontent.com/assets/7748162/3530343/93a4b680-07a3-11e4-89c5-ae64571e1a07.png)

It's easy to spot the cosmics lying over Mars, and the one in the upper right, but others are less apparent.

Overall, however, I think Max was right when he suggested that there are, compared to WFPC2, fewer cosmics in ACS/HRC images. I had suggested that this might be because the instrument is less easily saturated, and, indeed, there are cosmic-looking things that aren't nearly as bright as their other fellows. But the the relative paucity of cosmics is more likely due primarily to shorter exposure times, since ACS/HRC is much more sensitive than WFPC2.

In any case, if you start increasing `sigclip`, starting from 0, and increasing by 0.5 each image going left to right, you get what's below. The upper-left, blue-boxed image is the original.

![screen shot 2014-07-09 at 3 04 16 pm](https://cloud.githubusercontent.com/assets/7748162/3530014/195156a2-07a0-11e4-8b59-3cbfdef84a44.png)

It's probably helpful to open the image in a separate window. This section of the Mars image shows the interior of Mars, its limb, and three likely cosmics off to the upper left of the image, amongst the noise off Mars's limb.

Below are plots of where cosmicx changed pixels, in order of increasing value of `sligclip`. At low values, cosmicx basically marks everything on Mars's limb, everything outside it,  and even a lot of the pixels within it, as cosmic rays. 46% of the pixels have their values changed.

![screen shot 2014-07-09 at 2 44 19 pm](https://cloud.githubusercontent.com/assets/7748162/3530015/1d1e75d0-07a0-11e4-9165-56a257aec930.png)

As you increase `sigclip`, eventually cosmicx just starts chewing on the fuzz bordering Mars's limb. Practically any value of `sigclip` manages to clean up the cosmics outside of Mars. Unfortunately, I've yet to find a combination that manages to catch what are to me the most noticeable cosmics lying inside Mars:

![screen shot 2014-07-09 at 4 33 58 pm](https://cloud.githubusercontent.com/assets/7748162/3530875/499f08b4-07a9-11e4-8b66-0ea4b318fd51.png)

As before, the upper leftmost image is the original, and from there we have the CR rejected images, with increasing values of `sigclip`, starting from 0. At no point does cosmicx start catching these CR's, near the limb, which is surprising to me. Maybe they're not actually cosmics? But I think it's also likely that the algorithm's just plain bad at catching cosmics on highly luminous, somewhat varying extended backgrounds, like Mars. Images of planets are certainly not what the algorithm was developed for.

Since I haven't been able to find a combination of settings that let us get all of the CRs out, I'd recommend settings that minimize the spurious changes to the image. I don't know how important it is from a science perspective to preserve the "fuzz" around the limb, but as you increase `sigclip` it looks more and more like the content of the original image. Although, again, if you're using more prosaic scale settings, you wouldn't notice the fuzz anyway. I'd say a `sigclip` of 6 or 7 should do, although honestly I don't see the disadvantage of pushing it all the way up to 9, as it is in the rightmost, bottom image.

This all for ACS / HRC. I've yet to examine other cameras on ACS. I have a hunch that [the original WFPC2 settings](http://www.astro.yale.edu/dokkum/lacosmic/pars.html) should work for WFC, since ACS WFC fields tend to be assorted point sources with few, if any, extended objects (like the fields the LA-Cosmic algorithm was developed for). I don't know about SBC yet.

**Comment by ktfhale** [comment]
Is ACS/SBC immune to cosmic rays, due to being a photomultiplier and not a CCD? Certainly its unprocessed images don't seem to have them. Or, at least, it's very hard to distinguish them from what SBC data normally looks like - a fuzz of points.

![screen shot 2014-07-21 at 2 31 54 pm](https://cloud.githubusercontent.com/assets/7748162/3648031/5f05a1c6-1105-11e4-86f0-cad9dd20ff02.png)

When run on SBC images, CR rejection mainly picks up on the bars that frequent the images, sharp edges that obviously aren't due to cosmic rays. Unless I'm mistaken about what cosmic rays look like for SBC, I think we might be able to forego CR rejection entirely for our SBC dataset.

**Comment by acviana** [comment]
Max would have to weigh in on that.

**Comment by ktfhale** [comment]
Max wasn't sure about ACS/SBC and CR's, and suggested I find someone who worked with it. He also told me that WFC3/IR isn't subject to cosmic rays, due to the way the data is read out. So that's some good news.

 But we also discovered two issues.

First, turns out the `cosmics.py` parameters established for WFPC2 don't suffice for `cosmicx`. Images of planets look okay with a min/max stretch, but with a zscale stretch it becomes pretty clear something's wrong.

A `cosmicx` cr-rejected WFPC2 image of Uranus, with a min/max stretch:
![screen shot 2014-07-22 at 10 20 39 am](https://cloud.githubusercontent.com/assets/7748162/3659151/79d7778a-11ab-11e4-83a1-fa5fd93e1bd4.png)
A `cosmicx` cr-rejected WFPC2 image of Uranus, with a zscale stretch:
![screen shot 2014-07-22 at 10 20 31 am](https://cloud.githubusercontent.com/assets/7748162/3659153/7d504194-11ab-11e4-8cad-b7af800fbd37.png)

The background has basically been smoothed over its entirety. `cosmicx` is finding CR's everywhere. And fainter fields are even more badly mangled.

Below are cr-rejected WFPC2 images of Europa, by `cosmicx` and `cosmics.py`:

![screen shot 2014-07-22 at 10 16 13 am](https://cloud.githubusercontent.com/assets/7748162/3659249/53ea3a34-11ac-11e4-991e-9af758f820d7.png)

CR rejection was run with almost the same parameters between `cosmicx` and `cosmics`. The only difference in `cosmicx` was the gain, which, rather than being set to 1 as it was for `cosmics`, was read from the image's header file. In this case, it was 15. I'll see what happens if I set it back down to 1.

You can see the second issue in the `cosmicx` image above. `cosmicx`, in fainter fields, often produces weird  dark blobs. They occur frequently in WFC dim CR rejected fields:

![j9mc10f4q_zoom](https://cloud.githubusercontent.com/assets/7748162/3659755/af404f64-11b0-11e4-9ae4-965dc2eb4b0f.png)

They're seemingly caused by particularly dark pixels in the original image. Pixels with very negative values relative to their surroundings result in larger, although less negative, regions of pixels around them after CR rejection in `cosmicx`. I don't recall noticing this with `cosmics.py`.

Note the red-boxed dark pixels before CR rejection:
![before2](https://cloud.githubusercontent.com/assets/7748162/3660113/45ce8c2c-11b4-11e4-971d-877badf4278c.png)
And after:
![after2](https://cloud.githubusercontent.com/assets/7748162/3660118/4ff98cba-11b4-11e4-98e1-e8363550d4f9.png)

While there is one very bad dark blob, around other dark (indeed, negatively-valued) pixels, there is a general darkening.

Here is a closeup of the most egregious blob, with the pixel values annotated. The worst blobs seem to occur when there is an actual cosmic ray nearby negative pixels, as is the case here.
![before](https://cloud.githubusercontent.com/assets/7748162/3660126/673ad17c-11b4-11e4-80ba-b845cd9d45ff.png)
![after](https://cloud.githubusercontent.com/assets/7748162/3660128/6933d26c-11b4-11e4-9fc1-3f8bb48cbc2d.png)
Weirdly, a lot of the negative pixels don't change at all, maintaing the same values as before. This is very strange behavior.

This only seems to occur in very faint fields. The pixel values in this field are generally between -10 and 10, excepting what seem pretty clearly cosmics, and the particularly dark negative pixels. I suppose it's possible that these low-magntiude pixel values are throwing things off? I'll try playing with the settings to see if I can get these blogs to go away, and also ask Lou whether he ever ran into anything like this.

**Comment by ktfhale** [comment]
I am pleased to report that if we simply turn the `gain` parameter back to 1, `cosmicx` WFPC2 images look perfectly normal again. 

![u9xe010fm](https://cloud.githubusercontent.com/assets/7748162/3661381/2a42379a-11c0-11e4-9d32-d5a8eea4d5b6.png)

Contrast the second image with the cr rejected version in the comment above.

The `ATODGAIN` card in this image's WFPC2 header had a value of 15, very different than the value of 1 that was previously hard-coded into the WFPC2 parameters. Perhaps the `ATODGAIN` card in the WFPC2 header does not mean the same thing as the `gain` parameter in the LA cosmics algorithm. Regardless, I'm eliminating the reading of `ATODGAIN` from `get_metadata`.

Note, however, that we're still producing black blobs... one appears in this image, near the right. In another of my WFPC2 sample images, a dark pixel with a value of -106 goes from
![screen shot 2014-07-22 at 12 39 34 pm](https://cloud.githubusercontent.com/assets/7748162/3661442/a7f58aac-11c0-11e4-8260-5d26e5608990.png) ![screen shot 2014-07-22 at 12 39 19 pm](https://cloud.githubusercontent.com/assets/7748162/3661443/a7f6f95a-11c0-11e4-8248-9db75a0b13d0.png)

So that still needs figuring out.

**Comment by ktfhale** [comment]
Lou Strolger echoed Max's suggestion to cut off the negative tail of the histogram. In the `add_metadata` branch, I'll have `run_cosmicx` set every value in the `numpy` array less than -10 to 0, before we deliver the numpy array to `cosmicx`. We'll set it exactly to so that it's effectively as good as setting a warning flag for that pixel.

**Comment by ktfhale** [comment]
That seems to have solved the problem, at least for WFC data. Thresholding any values below -10 to 0 causes `cosmicx` to treat dark pixels more reasonably. The worst-case blob from above is instead:

![screen shot 2014-07-22 at 4 53 45 pm](https://cloud.githubusercontent.com/assets/7748162/3665157/4588f25a-11e3-11e4-96b2-b04ac7dfb82b.png)![screen shot 2014-07-22 at 4 54 02 pm](https://cloud.githubusercontent.com/assets/7748162/3665163/503337c4-11e3-11e4-96d8-5c05987f8559.png) 

The region around the dark pixels is still darkened, but this is inevitable, as that's just the information around the CR. But the darkening is much more believable.

I'm a little concerned how this method can end up making some pixels brighter relative to their neighbors, whereas before they were darker. For instance, a pixel that was -20 will become brighter than a -10 neighbor when it becomes 0. This seems somehow worse to me than just setting the -20 pixel to -10...

Another small side effect occurs in the very faintest fields.
![screen shot 2014-07-22 at 4 56 38 pm](https://cloud.githubusercontent.com/assets/7748162/3665206/b7cbabbe-11e3-11e4-8814-bba156792672.png)
![screen shot 2014-07-22 at 4 56 46 pm](https://cloud.githubusercontent.com/assets/7748162/3665208/bf0ef08e-11e3-11e4-8087-93354ae7ff00.png)

Bad read-out registers in very faint fields appear to take on negative values in the [-40,-20] range. The bad registers more or less disappear after cosmic ray rejection. For slightly brighter fields, where the pixels in the bad registers nonetheless have positive values, the register errors persist:

![screen shot 2014-07-22 at 4 57 38 pm](https://cloud.githubusercontent.com/assets/7748162/3665233/f56561a4-11e3-11e4-8fb6-5e235bde0dc4.png)
![screen shot 2014-07-22 at 4 57 49 pm](https://cloud.githubusercontent.com/assets/7748162/3665234/f62e7be8-11e3-11e4-9b36-1aacd195dfb9.png)

I'm running this modified CR rejection procedure it on the other detectors now. Overall, the results seem actually to be a better, and not just due to the absence of holes. Maybe CR rejection just works better when there's not a massive range, as was (artificially) imposed by those huge negative pixels.

**Comment by ktfhale** [comment]
CR rejection using this thresholding looks good on the four instruments. Out of WFC, WFPC2, UVIS, and HRC, I might want to play a little bit more with the UVIS settings, but for the others I think it might be as good as we're going to get. 

Some CRs near the limb of planets, or inside them, are still getting overlooked, but in my experience there's not much that can be done about that without changing the `satlevel` to a value inappropriate for the other CRs, or changing the `sigclip` such that the limb itself is sometimes eaten. There's not many of these CRs, though, and I think it's better that they remain there for astronomers to spot and recognize as CRs than to risk settings which could be deleterious to the targets.

Tomorrow I think I'll spend an hour or so fiddling with the UVIS parameters. Then, I'll add a few if-statements to exclude ACS/SBC and WFC3/IR from cosmic ray rejection, since those instruments don't need it. Then, I believe we can run the pipeline up to drizzling for all of our data.

**Comment by ktfhale** [comment]
I've improved the UVIS parameters. It now manages to reject a lot more cosmics that were within the extended limbs of planets in  certain images. I've also added the logic to keep cr rejection from running on IR and SBC data. I think we're ready to run CR rejection on all of our data.

**Comment by ktfhale** [comment]
All of these changes were made to the `add_metadata` branch. This branch just passed its latest Travis build, and I've run it successfully on inputs from all six detectors, using the `no-astrodrizzle` and `no-png` flag. I think the branch is ready to be merged. I'll submit a pull request.
