### ISSUE TITLE
README Update 

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#135]
As part of the final roll out of this project we will need to make a well-documented README file that completely captures all the information needed to install and run the pipeline. It should also contain information on all the processing steps and what they entail to ensure transparency and reproducibility.

**Comment by acviana** [comment]
I can take the first stab at this. I'll push my changes.

**Comment by ktfhale** [comment]
I've added an installation guide to the readme. It is as yet untested.

**Comment by ktfhale** [comment]
I'm in the process of updating the README's usage guide, and adding more detail on the various steps in the image processing pipeline.

I was curious to what extent we should use images within the README. For instance, in the aside on why we do not use CTE correction, should I include my difference maps of a CTE correction acting on point sources and extended sources? Should I show before and after examples of cosmic ray rejection? I know we wanted to include examples of the png preview images.
