### ISSUE TITLE
Merge build_master_finders_table.py and jpl2db.py

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#136]
As @walyssonBarbosa  pointed out in Issue #133, the functionality to fully populate the `master_finders` table is split between two modules: `build_master_finders_table.py` and `jpl2db.py`. This was a result of poor planning on my part over a year and a half ago when I was first creating these scripts.

I would be idea to merge the functionality of the two scripts into  `build_master_finders_table.py` so that it fully populates the `master_finders` table as the module name suggests.

The basic format is this:
- Iterate over the file list
- Grab the header information 
- Translate any header information as needed and populate a record dictionary
- Query JPL via the CGI
- Transform the JPL results and populate the same record dictionary as above.
- Create an instance of the MasterFinders class with the record dictionary and add it to the session.
- Periodically commit the session object.

**Comment by walyssonBarbosa** [comment]
Could you take a look at `def run_ephem_main(reproc=False):`? I left it commented out because I don't think we need to use it but maybe you want to keep it.

**Comment by acviana** [comment]
I'm going to branch off your branch to work on cleaning out some of the code I don't think we need anymore and some formatting. I'll send you a PR to pull the changes back into your branch if they look OK to you once I'm done. Should get to this today.

**Comment by acviana** [comment]
This is mostly done. The remaining issues will be cleaned up before we merge back into `master`.
