### ISSUE TITLE
Process ACS and WFC3 images to database

### ISSUE THREAD

**Issue by walyssonBarbosa** [STScI-Citizen-Science/MTPipeline#146]
Run `build_master_images_table.py` on `acs` and `wfc3` files.

**Comment by walyssonBarbosa** [comment]
What `png` files do I need to use? Only the `*_single_sci_linear.png` one or I am missing some of them?

**Comment by ktfhale** [comment]
We care about `*wide_single_sci_linear.png` and `*wide_single_sci_log.png` files.

However, we don't care about the `*center_single*` files at all, but they're still there. If desirable, I could delete them. However, the `update-master-finders` branch still expects to see them, so that version of the pipeline will reprocess the pngs if I get rid of the center images, and that would be bad. The current version of the master branch does _not_ expect center images, however, so if you're running that, then deleting the center images would be fine.

**Comment by walyssonBarbosa** [comment]
As I'm only going to work on filling up `master_images` I think it will not be a problem using `update-master-finders` because `build_master_images_table.py` will not make any changes in the filesystem. I will use `*wide_single_sci_linear.png` and `*wide_single_sci_log.png` instead of `*_single_sci_linear.png and *wide_single_sci_log.png`.

**Comment by ktfhale** [comment]
That looks great!

**Comment by walyssonBarbosa** [comment]
The script is breaking at line `75`:

``` python
master_images = MasterImages(header, fits_file, png_file)
```

It doesn't find the `FILTNAM1` keyword in the `fits` file, which is the first filter name for `wfpc2`.

**Comment by walyssonBarbosa** [comment]
In `master_images`, this keyword is the description column.

**Comment by walyssonBarbosa** [comment]
I started testing only with `acs`. So, I will change the `wfpc2` keyword to the one present in an `acs` `fits` file, I found out that it's `FILTER1`. If it's not this one we can change later.

**Comment by walyssonBarbosa** [comment]
I added this changes to `database_interface.py` so that I could work on the `acs` files:

``` python
Class MasterImages(Base):
    ...
    def __init__(self, header, fits_file, png_file):
        ...
        if '_c0m' in fits_file:
            self.description = header['FILTNAM1']
        else:
            self.description = header['FILTER1']
        ...
        if cr_mode == 'c0m' or cr_mode == 'wide':
            cr_mode = 'no_cr'
        ...
    ...
```

And this in `build_master_images_table.py`:

``` python
def build_master_images_table_main(png_file_list, reproc, reproc_sets):
       ...
        if '_linear.png' in png_file:
            fits_file = png_file.replace('png/','').replace('_linear.png','.fits')
        elif '_log.png' in png_file:
            fits_file = png_file.replace('png/','').replace('_log.png','.fits')
        ...
```

**Comment by walyssonBarbosa** [comment]
I finished populating `master_images` with `acs` and `wfc3` `*_wide_single_sci_linear.png` images.

**Comment by walyssonBarbosa** [comment]
No longer relevant as we no longer use `png` files as the `primary key`.
