### ISSUE TITLE
Wally's Computer Setup

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#78]
These are all the activities that are necessary to setup your machine for our project as well as some background reading. Please add any notes to the ticket you think might be useful for Kevin.
### ITSD
- Ask ITSD to add you to the `mtpipe` unix group (support@stsci.edu).  Cc: me so I can give them my approval
- Ask ITSD to build MySQL on your laptop (same as above)
- Go to http://www.stsci.edu/institute/itsd/hardware/printers and follow the Mac OSX instructions for setting up your printer. Print something to test your setup.
### Environment
- Install the basic version ureka, not SSBX or SSBDEV and read the docs (http://ssb.stsci.edu/ureka/). Ureka creates an Python/IRAF astronomy enviorment. Use ureka as your base development environment from now on. To get an idea of what ureka is doing run the following commands and notice how your enviorment variables change:

``` ShellSession
$ which python
$ echo $PATH
$ ur_setup
$ which python
$ echo $PATH
```
- In the eureka environment use `pip` to install `virtualenvwrapper` and read the docs (http://virtualenvwrapper.readthedocs.org/en/latest/). Use the following commands to do this:

```
$ which virtualenvwrapper
$ pip install virtualenvwrapper --upgrade
$ which virtualenvwrapper
```
- Now that you've installed `virtualenvwrapper` you can use this to build isolated development environments for you code. Let's say you're working on 2 features at the same time, Feature A and Feature B. Having a separate development environment ensures that your work on Feature A and Feature B stays separate until you merge them into the master branch (I'll explain all these terms soon). Let's go ahead and set up your first environment.  We'll use this one for a copy of the production code: the `master` branch:

```
$ cd ~
$ mkdir virtualenvs
$ cd virtualenvs
$ virtualenv mtpipeline-production
$ cd mtpipeline-production/
$ source bin/activate.csh
```

Now check your `$PATH` variable as well as where your `python` executable points as we did before to see what changed.
- Now that we have created a new environment for our `master` branch let's put some code in it. Let's start by building our main dependency, cloning our github repository, and installing a development version of our code with the following commands:

```
$ mkdir virtualenvs
$ cd virtualenvs
$ virtualenv mtpipeline-production
$ cd mtpipeline-production/
$ source bin/activate.csh
$ pip install numpy
$ git clone https://github.com/STScI-Citizen-Science/MTPipeline.git
$ cd MTPipeline/
$ python setup.py develop
```
### Background and Git Tutorial
- Complete the GitHub `git` tutorial: https://try.github.io/
-  Read the [Code Specs and Developer Workflow](https://github.com/STScI-Citizen-Science/MTPipeline/wiki/Code-Specs-and-Developer-Workflow)
- Read the following for project background. Ask Alex for copies:
  -  Planet Pipeline EPO Proposal
  - AR Solar System Phase 1
  - 2013 Fall DDRF Proposal

**Comment by walyssonBarbosa** [comment]
- Send ITSD an email asking them to add you in the group. They will wait until Alex grants permission so that they can add you in the mtpipe group.

**Comment by walyssonBarbosa** [comment]
- After you send ITSD an email about MySQL, they will request you your hostname. You can find it by going to System Preferences and then Sharing, it's the name displayed in Computer Name. Then, if you are connected to Ethernet or to the Internal Wireless they will be able to install MySQL on your laptop.

**Comment by acviana** [comment]
I realized that because I made the ticket you can't check the boxes. I'll think about if I want to change that or not because it also comes with other privileges such as push to the master branch which I wanted to restrict. 

As for the build don't get the dev version, version 1.0 is the one you want: http://ssb.stsci.edu/ureka/1.0/

**Comment by acviana** [comment]
I forgot to mention, once you install ureka, install virtualenvwrapper -in- the ureka environment. Actually, do all your work in the ureka environment. Like this:

``` shell
$ which python
$ echo $PATH
$ ur_setup
$ which python
$ echo $PATH
```

See the difference? Now run:

``` shell
$ which virtualenvwrapper
$ pip install virtualenvwrapper --upgrade
$ which virtualenvwrapper
```

**Comment by walyssonBarbosa** [comment]
After installing virtualenvwrapper, run:

```
$ mkdir virtualenvs
$ cd virtualenvs
$ virtualenv mtpipeline-production
$ cd mtpipeline-production/
$ source bin/activate.csh
$ pip install numpy
$ git clone https://github.com/STScI-Citizen-Science/MTPipeline.git
$ cd MTPipeline/
$ python setup.py develop
```

**Comment by acviana** [comment]
I think we can close this ticket right?

**Comment by walyssonBarbosa** [comment]
Jim has not contacted me about MySQL yet. Tomorrow I will pass by the ITSD to solve this issue.

**Comment by walyssonBarbosa** [comment]
MySQL done! We can close this ticket now.
