### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#82]
The `setup.py` file needs a `stwcs` dependency added.

**Comment by acviana** [comment]
Actually according to @walyssonBarbosa's notes on #81 there are a few other dependencies that need to be added as well.

**Comment by ktfhale** [comment]
The pipeline, including Wally's changes, appears to install and run just fine with the change and dependencies I added to `setup.py`. An `stwcs` dependency is never explicitly declared anywhere in it, however. We should probably test this on one of the linux virtual machines as soon as possible.

**Comment by ktfhale** [comment]
I've added `stwcs` into the install_requires argument of `setup.py`, pushing directly onto the master branch.

**Comment by acviana** [comment]
I think we can close this then.
