### ISSUE TITLE
Process Missing WFPC2 Imaging Data

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#86]
Using the outputs of `check_file_completeness.py` as a metric, run the `run_imaging_pipeline.py` script until there are no remaining missing files.

The first step in this process is just to get the script to run, this will likely take some installing of packages.

**Comment by acviana** [comment]
To check the number of extensions look here: http://astropy.readthedocs.org/en/latest/io/fits/.

Let me know what you find.

**Comment by walyssonBarbosa** [comment]
The file where the script crashes is `/astro/3/mutchler/mt/drizzled/05489_vesta/u2j70506t_cr_c0m.fits`.

When I run: 

``` python
hdulist = fits.open('/astro/3/mutchler/mt/drizzled/05489_vesta/u2j70506t_cr_c0m.fits')
hdulist.info()
```

This is the output:

```
Filename: /astro/3/mutchler/mt/drizzled/05489_vesta/u2j70506t_cr_c0m.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     234   ()   
```

**Comment by acviana** [comment]
Perform two comparisons first with `u2j70506t_c0m.fits` and then with the other '*_cr_com.fits' files in the folder. If you're not seeing anything obvious try another folder and see if you get the same error.

**Comment by walyssonBarbosa** [comment]
Here is the output for `u2j70506t_c0m.fits`:

``` python
Filename: /astro/3/mutchler/mt/drizzled/05489_vesta/u2j70506t_c0m.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     235   ()              
1    SCI         ImageHDU       176   (800, 800)   float32   
2    SCI         ImageHDU       176   (800, 800)   float32   
3    SCI         ImageHDU       176   (800, 800)   float32   
4    SCI         ImageHDU       176   (800, 800)   float32   
5    D2IMARR     ImageHDU        12   (800,)       float32 
```

**Comment by walyssonBarbosa** [comment]
All of the remaining `c0m.fits` and `cr_c0m.fits` files in this folder have more than one extension. Only `u2j70506t_cr_c0m.fits` doesn't have them.

**Comment by walyssonBarbosa** [comment]
Shouldn't the script only run over `c0m.fits` files?

I just ran it on `05782_saturn` folder and it's `Running png` right now. There 672 missing png files in this folder.

**Comment by acviana** [comment]
Ok. That's an anomaly then. Run it over a different folder and see if the missing file counts drop. Well look at how to fix that one weird file later today.

**Comment by walyssonBarbosa** [comment]
The process on folder 05782_saturn completed. But this error appears everytime the script is trying to write in disk:

``` python
IOError: IOError(... denied')
> /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/imaging/imaging_pipeline.py(143)imaging_pipeline()
-> run_astrodrizzle(filename)
(Pdb) where
  /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/scripts/production/run_imaging_pipeline.py(130)<module>()
-> run_imaging_pipeline()
  /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/email_decorator.py(43)wrapped()
-> func(*a, **kw)
  /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/scripts/production/run_imaging_pipeline.py(120)run_imaging_pipeline()
-> reproc_switch = args.reproc)
> /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/imaging/imaging_pipeline.py(143)imaging_pipeline()
-> run_astrodrizzle(filename)
  /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/imaging/run_astrodrizzle.py(114)run_astrodrizzle()
-> rename_files(filename, mode, output_path)
  /Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/imaging/run_astrodrizzle.py(91)rename_files()
-> shutil.copyfile(filename, dst)
  /Users/wbarbosa/STScI/ssbx/python/lib/python2.7/shutil.py(83)copyfile()
-> with open(dst, 'wb') as fdst:
```

**Comment by walyssonBarbosa** [comment]
Maybe it's because I don't have permission to do that. But I remember you giving me permission to do that yesterday.

**Comment by acviana** [comment]
I have set all the png/ folders to `775` and all the PNG files to `664`.

**Comment by walyssonBarbosa** [comment]
I don't know why but it didn't work. When it tries to rename the astrodrizzle files, it crashes.

**Comment by acviana** [comment]
Ok, I renamed the FITS files too, try it again.

**Comment by walyssonBarbosa** [comment]
It seems like it worked. I will leave it running to see if the files are created.

**Comment by walyssonBarbosa** [comment]
There are some corrupted files in `05782_saturn` like `/astro/3/mutchler/mt/drizzled/05782_saturn/u2on0101t_cr_c0m.fits`:

``` python
Filename: /astro/3/mutchler/mt/drizzled/05782_saturn/u2on0101t_cr_c0m.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     249   ()   
```

**Comment by walyssonBarbosa** [comment]
This warning appeared:

```
Not reprocessing cr_reject files.
Not reprocessing astrodrizzle files.
Running png
/Users/wbarbosa/virtualenvs/completeness-test/MTPipeline/mtpipeline/imaging/run_trim.py:292: RuntimeWarning: invalid value encountered in divide
  self.data = (self.data / self.data.max()) * 255.
```

**Comment by acviana** [comment]
Yeah, but it kept running right?

**Comment by walyssonBarbosa** [comment]
Yes. And I noticed that the numbers are going down. Before it was missing 672 png files in `05782_saturn`, now it's missing 658 png files.

**Comment by acviana** [comment]
Great! :100:

**Comment by walyssonBarbosa** [comment]
So I checked folder `/astro/3/mutchler/mt/drizzled/05782_saturn/` and only `u2on0101t_cr_c0m.fits` is corrupted.

**Comment by acviana** [comment]
Ok, you can delete the `u2on0101t_cr_c0m*.fits` and try rerunning the pipeline. That should regenerate an uncorrupted filed.

**Comment by walyssonBarbosa** [comment]
Ok.

Should I wait the pipeline to stop creating the other files?

**Comment by walyssonBarbosa** [comment]
I deleted `u2on0101t_cr_c0m*.fits` and `u2j70506t_c0m*.fits` and put the pipeline to run again on all the folders. The latter one is in folder `/astro/3/mutchler/mt/drizzled/05489_vesta/` which doesn't have any file missing anymore.

I need to go to my apartment now because I forgot my cellphone charger. If you need me here send me an email. If something happens during the execution of the pipeline I will receive an email about it.

**Comment by acviana** [comment]
Ok, I'll come by around 5 and we can discuss what do to next.

**Comment by acviana** [comment]
OK the next step is run this is production environment. Using the VM host I told you about (don't expose host names, usernames, or passwords on GitHub) set up the following:
- Install ureka
- Clone our repo
- Set up the settings.yaml file
- Make sure you are using the branch with all your current changes.
- Start a Screen session: http://acviana.github.io/posts/2013/the-joy-of-screen/
- Start up ureka
- Run the pipeline and detach the Screen session.

**Comment by walyssonBarbosa** [comment]
So, here's what I am trying to do:

```
$ ds9 -fits /astro/3/mutchler/mt/drizzled/05590_comet_sl/u2640101t_cr_c0m_center_single_sci.fits
```

It opens `SAOImage ds09` and it displays an image of the comet.

I should run this and `ds9 -fits /astro/3/mutchler/mt/drizzled/05590_comet_sl/u2640101t_cr_c0m_center_single_sci.fits` and check if the png files are the same as these two images, right?

**Comment by walyssonBarbosa** [comment]
The process was killed again. I didn't receive any email.

**Comment by acviana** [comment]
Find the image that killed the process, try running it individually. Inspect the file, look at the logs, drop in the debugger, see if you can determine what's going on.

**Comment by walyssonBarbosa** [comment]
I ran it individually and it completed. I inspected the file and it has all 4 extensions. The log didn't say why it stopped running. I will try to look for the reason by debugging.

**Comment by walyssonBarbosa** [comment]
The process was killed again:

```
Done running png
Not reprocessing cr_reject files.
Not reprocessing astrodrizzle files.
Running png
Killed
```

I thought this was happening in `run_trim.py`, so I put `pdb` there. However, iI couldn't catch the exception and stopped running before I could do that.

**Comment by walyssonBarbosa** [comment]
I put the pipeline to run on `science3` and it ran until the processes was killed at this morning 4am.

From 6:21pm yesterday to the time the process was killed, the pipeline created 2394 files, including png and the other fits files.

The virtual machine took 52min26s (03:05:22AM - 03:58:48AM) to run the pipeline on `08580_saturn_titan`. Within this time the pipeline created 252 png files.

**Comment by acviana** [comment]
Good, so break this down for me a little more. I'd like to see an apples-to-apples comparison of average time it took to complete each step on both machines. You should be able to use the log information to figure out the start and end time for each step and then take the average, mean, and std. This could probably be done easily in an IPython notebook. Note that the `datetime` object is useful for differencing time objects.

Include information about the CPU and memory in each machine. We need to understand if these processes are CPU, IO, or memory limited if we want to improve the performance.

**Comment by walyssonBarbosa** [comment]
Using this script in IPython notebook I could make some initial calculations on `/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-18-11-07.log`:

``` python
import datetime as dt
times_dict = {}
file_key = ''
time_calc = {'avg': 0, 'sum': 0, 'std': 0, 'count': 0, 'var': 0, 'sum_var': 0}
f = open('/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-18-11-07.log','r')
lines = list(f)
for line in lines:
    list_line = line.split(' ')
    if list_line[-2] == 'User:':
        print  'User: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Host:':
        print 'Host: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Count:':
        print 'CPU Count: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Memory:':
        print 'Memory: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'filelist:':
        print 'Filelist: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'File:':
        file_key = list_line[-1].replace('\n', '')
        times_dict[file_key] = []
        times_dict[file_key].append(list_line[-6])
    if list_line[-2] == 'Completed:':
        times_dict[file_key].append(list_line[-5])
        start_dt = dt.datetime.strptime(times_dict[file_key][0], '%H:%M:%S')
        end_dt = dt.datetime.strptime(times_dict[file_key][1], '%H:%M:%S')
        diff = (end_dt - start_dt)
        times_dict[file_key].append(diff)
        time_calc['sum'] += diff.seconds
        time_calc['count'] += 1
time_calc['avg'] = time_calc['sum'] / time_calc['count']
for key in times_dict.keys():
    time_calc['sum_var'] += (times_dict[key][2].seconds - time_calc['avg'])**2
time_calc['var'] = time_calc['sum_var'] / time_calc['count']
time_calc['std'] = (time_calc['var'])**0.5
print 'Mean: {0} seconds\nSTD: {1:.2f} seconds'.format(time_calc['avg'], time_calc['std'])
```

So what it does is it calculates the time the pipeline takes to run separated files and then it calculates the mean and the standard deviation. This was the result for this first try:

```
User: wbarbosa
Host: science2.stsci.edu
CPU Count: 12
Memory: 126GB
Filelist: /astro/mtpipeline/mtpipeline_outputs/wfpc2/07428_comet_tempel_tuttle/*c0m.fits
Mean: 96 seconds
STD: 5.48 seconds
```

PS: I didn't separate each process for png and other fits files because this log only had png processing information.

**Comment by walyssonBarbosa** [comment]
Here is the updated script:

``` python
import datetime as dt
times_dict = {}
file_key = ''
time_calc_dict = {'cr_reject': {'avg': 0, 'sum': 0, 'std': 0, 'count': 0, 'var': 0, 'sum_var': 0}, 
                  'astro': {'avg': 0, 'sum': 0, 'std': 0, 'count': 0, 'var': 0, 'sum_var': 0}, 
                  'png': {'avg': 0, 'sum': 0, 'std': 0, 'count': 0, 'var': 0, 'sum_var': 0}}
f = open('/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-10-13-22.log','r')
lines = list(f)
for line in lines:
    list_line = line.split(' ')
    if list_line[-2] == 'User:':
        print  'User: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Host:':
        print 'Host: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Count:':
        print 'CPU Count: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'Memory:':
        print 'Memory: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'filelist:':
        print 'Filelist: {}'.format(list_line[-1].replace('\n', ''))
    if list_line[-2] == 'File:':
        file_key = list_line[-1].replace('\n', '')
    if list_line[-2] + list_line[-1] == 'Runningcr_reject\n':
        times_dict[file_key] = {'cr_reject': [list_line[-5]]}
    if list_line[-3] + list_line[-2] + list_line[-1] == 'Donerunningcr_reject\n':
        times_dict[file_key]['cr_reject'].append(list_line[-6])
        start_dt = dt.datetime.strptime(times_dict[file_key]['cr_reject'][0], '%H:%M:%S')
        end_dt = dt.datetime.strptime(times_dict[file_key]['cr_reject'][1], '%H:%M:%S')
        diff = (end_dt - start_dt)
        times_dict[file_key]['cr_reject'].append(diff)
        time_calc_dict['cr_reject']['sum'] += diff.seconds
        time_calc_dict['cr_reject']['count'] += 1
    if list_line[-2] + list_line[-1] == 'RunningAstrodrizzle\n':
        times_dict[file_key] = {'astro': [list_line[-5]]}
    if list_line[-3] + list_line[-2] + list_line[-1] == 'Donerunningastrodrizzle\n':
        times_dict[file_key]['astro'].append(list_line[-6])
        start_dt = dt.datetime.strptime(times_dict[file_key]['astro'][0], '%H:%M:%S')
        end_dt = dt.datetime.strptime(times_dict[file_key]['astro'][1], '%H:%M:%S')
        diff = (end_dt - start_dt)
        times_dict[file_key]['astro'].append(diff)
        time_calc_dict['astro']['sum'] += diff.seconds
        time_calc_dict['astro']['count'] += 1
    if list_line[-2] + list_line[-1] == 'Runningpng\n':
        times_dict[file_key] = {'png': [list_line[-5]]}
    if list_line[-3] + list_line[-2] + list_line[-1] == 'Donerunningpng\n':
        times_dict[file_key]['png'].append(list_line[-6])
        start_dt = dt.datetime.strptime(times_dict[file_key]['png'][0], '%H:%M:%S')
        end_dt = dt.datetime.strptime(times_dict[file_key]['png'][1], '%H:%M:%S')
        diff = (end_dt - start_dt)
        times_dict[file_key]['png'].append(diff)
        time_calc_dict['png']['sum'] += diff.seconds
        time_calc_dict['png']['count'] += 1
for key in time_calc_dict.keys():
    if time_calc_dict[key]['count'] != 0:
        time_calc_dict[key]['avg'] = time_calc_dict[key]['sum'] / time_calc_dict[key]['count']
for file_key in times_dict.keys():
    for type_key in times_dict[file_key].keys():
        if len(times_dict[file_key][type_key]) == 3:
            time_calc_dict[type_key]['sum_var'] += (times_dict[file_key][type_key][2].seconds - time_calc_dict[type_key]['avg'])**2
for key in time_calc_dict.keys():
    if time_calc_dict[key]['count'] != 0:
        time_calc_dict[key]['var'] = time_calc_dict[key]['sum_var'] / time_calc_dict[key]['count']
        time_calc_dict[key]['std'] = (time_calc_dict[key]['var'])**0.5
        print '{0} files:\nMean: {1} seconds\nSTD: {2:.2f} seconds'.format(key, time_calc_dict[key]['avg'], time_calc_dict[key]['std'])
```

And here is the output for `/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-10-13-22.log`:

```
User: wbarbosa
Host: plvianav
Filelist: /astro/3/mutchler/mt/drizzled/*_*/*c0m.fits
cr_reject files:
Mean: 398 seconds
STD: 0.00 seconds
png files:
Mean: 790 seconds
STD: 66.34 seconds
```

**Comment by walyssonBarbosa** [comment]
Although we are using ssbx, I'm not able to run the pipeline in this folder `/astro/mtpipeline/mtpipeline_outputs/wfpc2/11990_comet_hartley2`

```
INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/11990_comet_hartley2/ubak1206m_c0m.fits
06/19/2014 10:36:44 AM INFO: Not reprocessing cr_reject files.
06/19/2014 10:36:44 AM INFO: Running Astrodrizzle
06/19/2014 10:36:45 AM CRITICAL: <type 'exceptions.ValueError'> Undefined variable `uref' in string `uref$sad1946fu_idc.fits' 113
```

UPDATE: The reason for that is that I was running the pipeline in the virtual machines and maybe something is missing on them.

**Comment by walyssonBarbosa** [comment]
I ran the script over all the log files and it showed that running the pipeline in science1, science2 or science3 takes about 100 seconds faster than running the pipeline in my laptop. Of course, that's for the png files.

**Comment by acviana** [comment]
Good. Fill out this table with your results:

| System | Cores | Memory | DRZ Avg | DRZ Std | CR Avg | CR Std | PNG Avg | PNG Std | File Count |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| wbarbosa | 4 | 8GB | 84.00 | 312.98 | 205.50 | 1055.23 | 211.33 | 195.50 | 10304 |
| plvianav | 4 | 3GB | 0.00 | 0.00 | 286.67 | 2095.28 | 311.29 | 1542.55 | 6862 |
| science1 | 8 | 31GB | 0.00 | 0.00 | 350.00 | 132.94 | 290.14 | 314.36 | 10736 |
| science2 | 12 | 126GB | 0.00 | 0.00 | 0.00 | 0.00 | 119.69 | 84.37 | 22344 |
| science3 | 24 | 62GB | 0.00 | 0.00 | 337.00 | 169.18 | 174.00 | 325.69 | 30182 |
| science4 | 64 | 252GB | 0.00 | 0.00 | 0.00 | 0.00 | 173.83 | 104.07 | 4900 |

**Comment by walyssonBarbosa** [comment]
I filled some of the values in the table, but I would need more time to check if they are all correct and to complete the script. The avg and std times are in seconds of time. The std values seem to be wrong, but I don't know if they are wrong or not.

Here are some info about the pipeline:
- Last week we processed 4366 files.
- This week we’ve already processed 51355 files
- 128289 files are missing

We are only able to process drizzle files in my laptop, every time I try to process them in the virtual machines that `uref` error appears.

**Comment by walyssonBarbosa** [comment]
Ok, I updated the table. I hope all the values are correct. The file count is not 100% correct because some files were reprocessed, but it's a close estimate.

An update about the pipeline:
- In the overall, we've already processed more than 96142 files
- There are less than 87868 missing files

I'm not able to process '11990_comet_hartley2' folder. The pipeline is going over `c1m.fits` files and they don't exist in the folder, so there's always an `IOError`.

**Comment by walyssonBarbosa** [comment]
Should I save this script in the repo? If so, where should it be?

**Comment by acviana** [comment]
Yes, I would save it in `scripts/checks/`. Push the changes to your branch so I can comment.

**Comment by walyssonBarbosa** [comment]
Table update:

| System | Cores | Memory | DRZ Avg | DRZ Std | CR Avg | CR Std | PNG Avg | PNG Std | File Count |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| wbarbosa | 4 | 8GB | 80.86 | 267.70 | 209.50 | 986.33 | 202.44 | 183.38 | 11256 |
| plvianav | 4 | 3GB | 0.00 | 0.00 | 286.67 | 2095.28 | 311.47 | 1542.43 | 7506 |
| science1 | 8 | 31GB | 0.00 | 0.00 | 350.00 | 132.94 | 270.00 | 347.62 | 22188 |
| science2 | 12 | 126GB | 0.00 | 0.00 | 0.00 | 0.00 | 131.11 | 194.33 | 36120 |
| science3 | 24 | 62GB | 49.33 | 20.28 | 419.00 | 240.00 | 166.45 | 248.20 | 49564 |
| science4 | 64 | 252GB | 35.00 | 14.74 | 230.29 | 34.59 | 123.19 | 87.40 | 57944 |

An update about the pipeline:
- In the overall, we've already processed more than 178148 files
- There are less than 5862 missing files

**Comment by walyssonBarbosa** [comment]
The pipeline has completed the process of creating all missing files:

```
$ cat /astro/mtpipeline/logs/check_file_completeness/check_file_completeness_2014-06-25-11-37.log | grep Missing:
06/25/2014 11:37:41 AM INFO: Missing: 0 files
```

**Comment by walyssonBarbosa** [comment]
Final table update:

| System | Cores | Memory | DRZ Avg | DRZ Std | CR Avg | CR Std | PNG Avg | PNG Std | File Count |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| wbarbosa | 4 | 8GB | 80.45 | 353.32 | 242.50 | 1505.56 | 178.45 | 258.31 | 11638 |
| plvianav | 4 | 3GB | 0.00 | 0.00 | 286.67 | 2095.28 | 311.47 | 1542.43 | 7506 |
| science1 | 8 | 31GB | 0.00 | 0.00 | 350.00 | 132.94 | 270.00 | 347.62 | 22188 |
| science2 | 12 | 126GB | 0.00 | 0.00 | 0.00 | 0.00 | 131.11 | 194.33 | 36120 |
| science3 | 24 | 62GB | 34.50 | 16.76 | 324.57 | 178.30 | 150.59 | 210.76 | 51512 |
| science4 | 64 | 252GB | 32.16 | 15.81 | 234.28 | 95.15 | 105.73 | 67.73 | 62776 |

**Comment by walyssonBarbosa** [comment]
I think we can close this, right?

**Comment by acviana** [comment]
Yes.
