### ISSUE TITLE
WFPC2 PNG Validation

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#87]
The PNG outputs of the imaging pipeline need to be validated to ensure that there are no up/down or left/right translations from the FITS files to the master PNG files and then again to the PNG subimages. 

We examined this last year from the master to png level to some degree in issue #70. 

For a more complete test the FITS images should be inspected with ds9 and compared to the PNG outputs to ensure there are no translations in either step.

**Comment by walyssonBarbosa** [comment]
I examined the images for the FITS file `/astro/3/mutchler/mt/drizzled/05215_mars/u2mi0101t_c0m.fits`.

The master PNG files and the PNG sub images appear to be correct. The sub images are in the same order as in they should be when comparing to `u2mi0101t_c0m_wide_single_sci.fits`.

**Comment by acviana** [comment]
Ok, I'll close this then.
