### ISSUE TITLE
Prototype JPL Data Collection with Pexpect

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#89]
The MT Pipeline uses the [JPL HORIZONS](http://ssd.jpl.nasa.gov/?horizons) system to generate [ephemerides](http://en.wikipedia.org/wiki/Ephemeris) (celestial positions) bodies in our dataset with moons. 

The process involves extracting pointing, date, and time data from the header keywords of each FITS file for objects with moons. Then for each moon in the system a request is sent to JPL for the coordinates at the date and time of the exposure. These coordinates are then transformed using the pointing information from celestial coordinates (Right Ascension and Declination) into pixel coordinates on the detector.

The critical step in this process that could be improved upon is the mechanism to interact with the JPL system. Originally, this was done using a TELNET interface but this had timeout issues as well as general performance issues. The function to do this can be found in `mtpipeline.ephem.jpl2db.telnet_session`.

After that web scraping approach was developed using an undocumented CGI interface (or at least it was at the time). This web interface was explained in an email from a HORIZONS developer. The function to do this can be found in `mtpipeline.ephem.jpl2db.cgi_session`.

In that same email they recommended using the UNIX `expect` command to automate interaction with the TELNET interface for the best results. One advantage is that the CGI function contains "wait" command to ensure that we do not hammer their webserver (to be nice). A TELNET session, even one automated with `expect` would not be subject to any such request limit.

So, the task here is to use the python [pexpect](http://pexpect.readthedocs.org/en/latest/examples.html) module to create a function that get the required data JPL. Prototype this an IPython notebook so you can use the `%%timeit` cell magic to compare the performance of the 3 methods.

Inspecting the ``mtpipeline.ephem.jpl2db.get_jpl_data` function should give an idea of the context for each function call. You do not need to iterate over all the moons for an exposure, just pick one and mock up a dictionary that means the minimum requirements for a `moon_dict` instance.

**Comment by ktfhale** [comment]
The standard telnet session is very slow, taking about 94 seconds to execute the commands given in `COMMAND_LIST` in `test_jpl2db.py`. The CGI method is a huge improvement, taking 5.3 seconds. The `pexpect` method is slightly faster, taking 4.4 seconds. Below is the draft function to replace `telnet_session()`:

```
def pexpect_session(command_list, verbose=False):
    """Issues commands to JPL's ephemeris over telnet using pexpect

    Parameters:
        command_list : list
            A list of strings of commands that JPL's ephemeris 
            recognizes. It is assumed to be of a very specific form,
            containing only 10 specific commands. 

        verbose : boolean
            If True, the ephemeris resposne will be printed at every
            step

    Returns:
        A string containing the final output from the ephemeris

    Outputs: nothing

    Examples: 

    clist = ['899', 'e', 'o', 'geo', 
            '1997-Jul-03 09:17', '1997-Jul-03 09:18',
            '1m', 'y','1,2,3,4,9,13', 'n']
    pexpect_session(clist, verbose=False)

    """

    assert len(command_list) == (10), "The command list is improperly formatted!"

    tn = pexpect.spawn('telnet ssd.jpl.nasa.gov 6775')
    tn.expect_exact('Horizons>')
    if verbose: print tn.before+tn.after

    tn.sendline(command_list[0])
    tn.expect_exact('[R]edisplay, ?, <cr>: ')
    if verbose: print tn.before+tn.after

    tn.sendline(command_list[1])
    tn.expect_exact('Vectors  [o,e,v,?] : ')
    if verbose: print tn.before+tn.after

    tn.sendline(command_list[2])
    tn.expect_exact('center [ <id>,coord,geo  ] : ')
    if verbose: print tn.before+tn.after

    tn.sendline(command_list[3])
    tn.expect_exact('Starting UT  [>=   1800-Jan-25 00:01] : ')
    if verbose: print tn.before+tn.after 

    tn.sendline(command_list[4])
    tn.expect_exact('UT  [<=   2199-Nov-28 23:58] : ')
    if verbose: print tn.before+tn.after 

    tn.sendline(command_list[5])
    tn.expect_exact('interval [ex: 10m, 1h, 1d, ? ] : ')
    if verbose: print tn.before+tn.after 

    tn.sendline(command_list[6])
    tn.expect_exact('output [ cr=(y), n, ?] : ')
    if verbose: print tn.before+tn.after 

    tn.sendline(command_list[7])
    tn.expect_exact('quantities [ <#,#..>, ?] : ')
    if verbose: print tn.before+tn.after 

    tn.sendline(command_list[8])
    tn.expect_exact('[R]edisplay, ? : ')
    if verbose: print tn.before+tn.after 

    data = tn.before+tn.after

    tn.sendline(command_list[9])
    #Returns back at 'Horizons>'

    tn.close()
    return data
```

While this function executes on the test input, and appears to return the lengthy string with what we want, its output has not yet been tested against the parser function.

**Comment by ktfhale** [comment]
Removing the 5 second delay from the CGI implementation, it now runs in less than a second, making it much faster than the `pexpect` method. As a result, a change has been committed to the `cosmicx` branch, in which that delay is deleted, and the docstring updated. As long as we don't hit JPL with more than a single request at a time, according to them we should be fine.
