### ISSUE TITLE
Initial Analysis of cosmics vs cosmicx

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#90]
I would like to compare two different implementations of the LA Cosmics cosmic ray rejection algorithm, `cosmics.py` and `cosmicx.py`. `cosmics.py` is currently implemented in our pipeline in `mtpipeline/imaging/run_cosmics.py`. These lines (82-91) show the implementation to process the 1st extension of a WFPC2 image:

``` python
c = cosmics.cosmicsimage(
                        array,
                        pssl = 0.0,
                        gain = 1.0,
                        readnoise = 1.0,
                        sigclip = 5.0, #3.0 -> 5.0
                        sigfrac = 0.01,
                        objlim = 4.0,
                        satlevel = 4095.0,
                        verbose = True)
```

Note that one difference in your prototyping use `astropy.io.fits` to open the FITS data instead of the `pyfits`. Also, I would recommend using the IPython notebook for this type of prototyping.

Starting with the README in the cosmicx tarball, see if you can produce the equivalent output from `cosmicx` and compare it with the output of `cosmics`. Time the execution time to see if there is a performance increase. You can use whatever file you like from `/astro/mtpipeline/mtpipeline_outputs/wfpc2/`

**Comment by ktfhale** [comment]
I'm trying to build the lacosmix package, and I have questions about these sections of its README file:

```
Installation instructions

1. build a 32 or 64-bit cfitsio lib, following the sndep/README instructions. 
    NOTE : as of 2011.08.23 the cfitsio lib can be compiled as either 32 or 64 bit. 
           It now only has to match whatever your python is built to. 

2. lacosmicx

  Curtis McCully's c++ with a python wrapper re-write of the Van Dokkum algorithm.
  This is the one dependency that lives within the snpipe tree instead
  of the sndep tree, as it is likely to get updated semi-regularly.
  To build it, go into the snpipe/lacosmicx directory:

    > cd {$SNTOP}/snpipe/lacosmicx/
```

I appear to have the `cfitsio` library already installed, but I don't know where `sndep`and `snpipe` are in my filesystem. `$SNTOP` is not a defined path on my system.

The lacosmix file `setup.mac.py` says this:

```
 # SNDEPDIR is the sndep directory, where you have already built a 32-bit
 # compilation of cfitsio, per the sndep README.  Typically this is adjacent
 # to the snpipe directory that lacosmicx resides in.
 # e.g. on Steve's mac:  SNDEPDIR = '/Users/rodney/src/hstsn/sndep'
 SNDEPDIR = os.path.abspath('../../sndep')
```

An `hstsn` directory is proving similarly elusive on my system. I suppose `SNDEP` might have been the original location where `cfitsio` was built. It looks to me like `cfitsio` lives in various directories inside `/Applications/ST_sci/heasoft-6.15.1`.

**Comment by ktfhale** [comment]
Incidentally, the support desk is currently installing MySQL on my laptop, so I am currently without it. I should have it back soon.

**Comment by acviana** [comment]
I'm comparing and contrasting `setup.py`, `setup.mac.py`, and `setup.strolger.py` which kind of gives me a better idea of what's going on, but not enough to answer your question. Googling `SNTOP` and `SNDEP` isn't giving me any clues (I don't think this is referring to unix utility `sntop`). I think it might be time to shoot off an email to Lou (per my email this morning). 

FYI, we'll likely have to rebuild a version of this `setup.py` into our own `setup.py` to use `setuptools` instead of `distutils` and combine them into a single install script. Normally, we wouldn't cannibalize someone else's code like this but there is no public repo to link to so IDK what else to do. But, that's for down the road once we get this up and running and decide it's an improvement over `cosmics.py`.

**Comment by ktfhale** [comment]
I'll send him an email asking about these instructions, then.

I'm pretty sure these directories and paths are all referring to the name of a project. `SNTOP` and `SNDEP` being the top-level directory for all the project's code and certain dependencies, respectively? Maybe it had something to do with supernovae. Hopefully, we can just do away with those directories, unless there's something else in that project that `lacosmicx` needs.

**Comment by ktfhale** [comment]
I'm working right now on cobbling together a makefile using `makefile.mac`, along with some of the other personalized ones, as a template. I feel pretty out of my depth. Sometime I'd like to get a primer on how the institute's software is organized from the top of the file tree. At the moment, I'm trying to decide which python to give for the include directory- do I want to use the one in Ureka on my own machine, or the one at `/sw/include/python2.7`? I think the latter's probably better.

EDIT: nevermind, Ariel has informed me its standard to use the local version from Ureka.

Then there's where the Makefile should look for the `cfits` include and library directories. One makefile just uses `/sw/include` and '/sw/lib` for those, respectively. That directory is still around. I imagine that's probably the way to go?

**Comment by ktfhale** [comment]
I was able to build the `cfitsio` library that`lacosmicx` needs, and then to finally build `lacosmicx`. `lacosmicx` is much faster, and produces a cleaned image that, with a visual inspection, seems little different than `cosmic`'s. Running on the image of mars `u2mi010lt_c0m.fits` (using's ds9's zscale):

![before](https://cloud.githubusercontent.com/assets/7748162/3333909/a5180eea-f7f8-11e3-8593-c16dd333d0c5.png)

`lacosmicx` produces:

![after_lacosmicx](https://cloud.githubusercontent.com/assets/7748162/3333924/cf4fde7c-f7f8-11e3-96c1-332198f6eb2b.png)

`cosmics.py` produces

![after_cosmics](https://cloud.githubusercontent.com/assets/7748162/3333978/659f6e56-f7f9-11e3-9e3c-1f3a52ce08df.png)

`cosmics` takes 145 seconds to run on all four significant extensions of this image.
'lacosmicx` takes 7 seconds.

They do not produce exactly the sam result. Below shows at what pixels on the 800x800 original image the two cleaned images differ.

![differ1](https://cloud.githubusercontent.com/assets/7748162/3341434/59fddd82-f888-11e3-90c7-c06432d7f9bf.png)

The edges of this image are poor, and the cleaning routines producing different results there are not surprising. There are some differences between the routines within the body of the image, however. 

In each extension, the number of pixels that had different values between the two rejection routines varied:

extension1: 15856 (~ 2% of total)
extension2: 41556 (~ 6% of total)
extension3: 42581 (~ 7% of total)
extension4: 49809 (~ 8% of total)

The histogram below, in which pixels that have _no_ difference are omitted, shows that the majority of differing pixels differ by less than 100 pixel units.

![differ2](https://cloud.githubusercontent.com/assets/7748162/3341573/a5e68f68-f889-11e3-9857-f68d19f3230a.png)

A single pixel exists with that differs by -8000 units, and is not displayed above.

**Comment by ktfhale** [comment]
I ran a few more images, to see if these results were representative. This was the most useful:

Before rejection:
![saturn_original](https://cloud.githubusercontent.com/assets/7748162/3342251/8bb1e938-f890-11e3-8698-b3c726f277bd.png)
`cosmics`
![saturn_cosmics](https://cloud.githubusercontent.com/assets/7748162/3342278/b7d1a45e-f890-11e3-828c-a4bec866f304.png)
`lacosmicx`
![saturn_lacosmicx](https://cloud.githubusercontent.com/assets/7748162/3342283/bd441732-f890-11e3-8aeb-a273053011f2.png)

`cosmics` did not reject two likely cosmics, one on the rings and another near the pole. `lacosmicx` did not reject one at the upper border of the image.

Across the 4 significant extensions, 6, 7, 8, and 9% of the pixels had different values, respectively.

![differs3](https://cloud.githubusercontent.com/assets/7748162/3342349/70ea2e16-f891-11e3-8dd4-e1097e956831.png)

There was a a greater magnitude overall in the pixel value differences, although the spread was fairly similar to the mars image's.

![differs4](https://cloud.githubusercontent.com/assets/7748162/3342351/77a8f1ec-f891-11e3-9aa4-5ecc2097ab60.png)

**Comment by ktfhale** [comment]
In case it is of interest, comparing the original saturn image to the cleaned image:

Under `lacosmicx`:

5, 6, 6, and 7% of the pixels were changed on each extension. This percentage is severely exaggerated by the edges, as a heat map comparing the original pixel values to the cleaned pixel values shows:

![rays_removed](https://cloud.githubusercontent.com/assets/7748162/3343357/da41227c-f89e-11e3-9791-340c1fff6317.png)

The solid orange background signifies no change in the pixel value. Yellow signifies a collection of pixels was identified as cosmic rays, and removed.

![rays_removed2](https://cloud.githubusercontent.com/assets/7748162/3343393/3a41b5f6-f89f-11e3-92aa-21f1b4d14352.png)

Under 'cosmics':

6, 7, 7, and 8% of the pixels were changed on each extension.

![rays_removed_cosmics](https://cloud.githubusercontent.com/assets/7748162/3343482/23a18938-f8a0-11e3-80a3-2b0bde2e3c79.png)

On this scale, red signifies no change.

![rays_removed_cosmics2](https://cloud.githubusercontent.com/assets/7748162/3343484/27e0bc58-f8a0-11e3-95ef-d8046b5ce826.png)

**Comment by ktfhale** [comment]
Overall, `lacosmicx` offers a significant speedup over `cosmics`. While the output of the two technically differ, to the eye they are quite similar, with `lacosmicx` actually producing outputs that look slightly better. Ultimately, both routines are effective at cleaning cosmic rays, and which is better at it is a fairly subjective criterion. Given that we feel the products of `lacosmicx` look better anyways, along with its significant increase in speed, we've decided to remove `cosmics` from our code, and implement `lacosmicx` instead.
