### ISSUE TITLE
Add outputs to setup_logging

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#91]
In the near future I would like to start analyzing some performance statistics for the imaging pipeline. In order to to that we'll need some more information. Add some logging commands to `mtpipeline/setup_logging` in the `setup_logging` function so that it always logs the following information:
- user
- hostname
- OS
- CPU count
- Total Physical memory size

You can get some of this information (and more) with `platform.uname()`. Also log the version number of the following packages:
- python
- astropy
- numpy
- sqlalchemy
- PIL

You can make this update in your current `imaging-pipeline-update` branch.

**Comment by walyssonBarbosa** [comment]
I needed to install the `psutil` module to get information about memory.

**Comment by acviana** [comment]
Do you think we're ready to merge these changes back into the `master` branch then?

**Comment by walyssonBarbosa** [comment]
I think we are. I did last commit because I had to add `psutil` to `setup.py`.

**Comment by acviana** [comment]
Let's wait until you commit the script you built in #86 .

**Comment by walyssonBarbosa** [comment]
Can I close this ticket?

**Comment by acviana** [comment]
Yes.
