### ISSUE TITLE
Parallelize Imaging Pipeline

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#94]
Now that you've created some metrics that allow us to track the performance of the WFPC2 pipeline we should look at paralleling it. This SO question gives a good overview of the available options using Python `Multiprocessing` library: http://stackoverflow.com/a/8533626/1216837 

Start by creating a simple mock-up in the ticket of how you think this could be applied to our pipeline.

**Comment by walyssonBarbosa** [comment]
So I thought about something like this script:

``` python
import multiprocessing as mp
import glob
import os
from mtpipeline.get_settings import SETTINGS
from scripts.production.run_imaging_pipeline import run_imaging_pipeline
from mtpipeline.setup_logging import setup_logging
from

result_list = []
def log_result(result):
    result_list.append(result)

def apply_async_with_callback():
    pool = mp.Pool(processes=mp.cpu_count()/2) # number of processors we want to use in the machine
   filelist = glob.glob(os.path.join(SETTINGS['wfpc2_output_path'], '*_*/*c0m*.fits'))
    for folder in filelist:
        pool.apply_async(run_imaging_pipeline, args = ('-filelist', folder), callback = log_result)
    pool.close()
    pool.join()
    print(result_list)

if __name__ == '__main__':
    setup_logging('run_imaging_pipeline')
    apply_async_with_callback()
```

Thus, `run_imaging_pipeline` would have to return something when it completed running the pipeline over that specific folder.

**Comment by acviana** [comment]
Can you explain some things to me:
1. What is `log_result` doing?
2. What does `pool.close()` do?
3. What does `pool.join()` do?
4. What are you using `apply_async` instead of `apply`?
5. How should we decide how many cores to use?

**Comment by walyssonBarbosa** [comment]
I just showed this script as an example from the SO script:
- `log_result` will store the messages that `run_imaging_pipeline` is returning (e.g. 'Script completed').
- `pool.close()` prevents any more tasks from being submitted to the pool. So it will wait until the processes that are running complete their execution to add more processes to the pool of execution.
- `pool.join()` waits for the processes to exit in order to continue with the rest of the script.
- If I understood the docs, using `apply` a process would have to wait another process to complete its execution to start executing. With `apply_async` the processes can execute concurrently.
- I don't know exactly how we should decide that. Maybe we could use a third of the cores? For example, if a machine has 12 cores we could use 4 of them to run the pipeline.

**Comment by acviana** [comment]
Also, this might be useful: http://seasonofcode.com/posts/python-multiprocessing-and-exceptions.html

**Comment by walyssonBarbosa** [comment]
I have modified `run_imaging_pipeline.py` to implement multiprocessing:

``` python
"""Script for executing the imaging_pipeline.

This module is used to execute the mtpipeline.imaging_pipeline code. 
It contains the logic for parsing the command line arguments, logging 
the execution, an email decorator to send out a end of script message, 
and a try/execpt loop to catch exceptions. 

Authors:
    Alex Viana, April 2014
"""

from mtpipeline.imaging.imaging_pipeline import imaging_pipeline
from mtpipeline import email_decorator
from mtpipeline.setup_logging import setup_logging

import multiprocessing as mp
import glob
import argparse
import logging
import os
import sys


def parse_args():
    """Parse the input arguments using `argparse` module.

    Parameters: 
        nothing

    Returns: 
        args : an instance of the class returned by 
        `parser.parse_args` with the arguments as instance attributes.

    Outputs:
        nothing
    """
    parser = argparse.ArgumentParser(
        description = 'Run the moving target pipeline.' )
    parser.add_argument(
        '-filelist',
        required = True,
        help = 'Search string for files. Wildcards accepted.')
    parser.add_argument(
        '-output_path',
        required = False,
        help = 'Set the path for the output. Default is the input directory.')
    parser.add_argument(
        '-no_cr_reject',
        required = False,
        action='store_false',
        default = True,
        dest = 'cr_reject',
        help = 'Toggle off the cosmic ray rejection step.')
    parser.add_argument(    
        '-no_astrodrizzle',
        required = False,
        action='store_false',        
        default = True,
        dest = 'astrodrizzle',
        help = 'Toggle off the astrodrizzle step.')
    parser.add_argument(
        '-no_png',
        required = False,
        action = 'store_false',        
        default = True,
        dest = 'png',
        help = 'Toggle off the png step.')
    parser.add_argument(
        '-reproc',
        required = False,
        action = 'store_true',
        default = False,
        dest = 'reproc',
        help = 'Reprocess all files, even if outputs already exist.')
    args = parser.parse_args()
    return args


def run_imaging_pipeline(filename):
    """The script for executing the imaging_pipeline function.

    This function is the wrapper for the `imaging_pipeline` function 
    in `mtpipeline`. It adds logging information and parses the 
    command line arguments returned by `parse_args`. Completion emails 
    are added by the `email_decorator` function. 

    Parameters: 
        nothing

    Returns: 
        nothing

    Outputs:
        The outputs of this are the same as the wrapped 
        `imaging_pipeline`.
    """
    logging.info("Current File: " + filename)
    try:
        imaging_pipeline(filename,
            output_path =  args_list.output_path,
            cr_reject_switch = args_list.cr_reject,
            astrodrizzle_switch = args_list.astrodrizzle,
            png_switch = args_list.png,
            reproc_switch = args_list.reproc)
        logging.info("Completed: " + filename)
    except Exception as err:
        logging.critical('{0} {1} {2}'.format(
            type(err), err.message, sys.exc_traceback.tb_lineno))

@email_decorator.email_decorator
def run():
    """
    """
    logging.info("Command-line arguments used:")
    for arg in args_list.__dict__:
        logging.info(arg + ": " + str(args_list.__dict__[arg]))
    rootfile_list = glob.glob(args_list.filelist)
    rootfile_list = [filename for filename
                     in rootfile_list
                     if len(filename.split('/')[-1]) == 18
                     and filename.split('/')[-1].split('_')[-1] == 'c0m.fits']
    assert rootfile_list != [], 'empty rootfile_list in mtpipeline.py.'
    logging.info('Processing: {} files'.format(len(rootfile_list)))
    pool = mp.Pool(processes=3) # Using three cores
    pool.map(run_imaging_pipeline, rootfile_list) # map divides the list in equal chuck sizes to distribute between the 3 processes
    logging.info("Script completed")

if __name__ == '__main__':
    setup_logging('run_imaging_pipeline')
    args_list = parse_args()
    run()
```

Although the pipeline is running, there's no writing control in the log file. It results in something like this:

```
06/26/2014 15:24:01 PM INFO: User: wbarbosa
06/26/2014 15:24:01 PM INFO: Host: itsd-summer11.stsci.edu
06/26/2014 15:24:01 PM INFO: Machine: x86_64
06/26/2014 15:24:01 PM INFO: Platform: Darwin-13.2.0-x86_64-i386-64bit
06/26/2014 15:24:01 PM INFO: CPU Count: 4
06/26/2014 15:24:01 PM INFO: Total Physical Memory: 8GB
06/26/2014 15:24:01 PM INFO: Python Version: 2.7.5
06/26/2014 15:24:01 PM INFO: Astropy Version: 0.3.2
06/26/2014 15:24:01 PM INFO: SQLAlchemy Version: 0.9.4
06/26/2014 15:24:01 PM INFO: PIL Version: 1.1.7
06/26/2014 15:24:01 PM INFO: Command-line arguments used:
06/26/2014 15:24:01 PM INFO: filelist: /astro/mtpipeline/mtpipeline_outputs/wfpc2/*_*/*c0m.fits
06/26/2014 15:24:01 PM INFO: cr_reject: True
06/26/2014 15:24:01 PM INFO: output_path: None
06/26/2014 15:24:01 PM INFO: reproc: False
06/26/2014 15:24:01 PM INFO: astrodrizzle: True
06/26/2014 15:24:01 PM INFO: png: True
06/26/2014 15:24:03 PM INFO: Processing: 10624 files
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Completed: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Completed: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Completed: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70507t_c0m.fits
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12002m_c0m.fits
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0309m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
```

**Comment by walyssonBarbosa** [comment]
I read about this new feature they wanted to include in Python 3.2 (I think there's already something similar in the new version of Python, I didn't look for it yet though): http://plumberjack.blogspot.com/2010/09/using-logging-with-multiprocessing.html

I will look for something similar to this or try to implement something similar.

I thought about creating a class `LogHandler` that would control the writing process in the log file. This class would have a `write_log` function to manage the writing in the log file. For example, in some moment, `run_imaging_pipeline` would call `write_log(message, level, process_name)`. Then, the `write_log` function would see if there's already a process writing some message to the log file. If there is, that new message would be added to a queue of messages to be written to the log file.

I don't know if this is clear. I will still try to find some feature easier to use.

**Comment by walyssonBarbosa** [comment]
Also, how would you like the log file to be structured?

For example, this way:

```
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
```

Or this:

```
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/10534_neptune/u9c12001m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing cr_reject files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing astrodrizzle files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/09052_mars/u6gq0308m_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
06/26/2014 15:24:03 PM INFO: Current File: /astro/mtpipeline/mtpipeline_outputs/wfpc2/05489_vesta/u2j70506t_c0m.fits
06/26/2014 15:24:03 PM INFO: Not reprocessing png files.
```

**Comment by acviana** [comment]
Could you explain the difference between the two outputs?

**Comment by walyssonBarbosa** [comment]
In the first one, the `LogHandler` would have to wait for the three processes in a specific file to complete so that it could write in the log file. Whereas in the second one, after each process, the `LogHandler` would be able to write in the log file. I don't know if the first one is affordable or not, meaning that I don't know if it would be a waste of cpu time.

**Comment by walyssonBarbosa** [comment]
Here is the doc for the module I said it was to be added to a newer Python version: https://docs.python.org/3.5/howto/logging-cookbook.html

**Comment by walyssonBarbosa** [comment]
I lost the changes I've made in `run_imaging_pipeline.py` and `setup_logging.py` when I tried to create a new branch. But I still have 70% of the code. But when I try to pull it back it seems to work and then it disappears.

I made a first parallelize attempt, when the pipeline completes its process it calls a function `organize_logfiles` in `setup_logging.py` that extracts the log information to their respective files:

```
$ ls /astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-27-15-42*.log
/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-27-15-42_MainProcess.log
/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-27-15-42_PoolWorker-1.log
/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-27-15-42_PoolWorker-2.log
/astro/mtpipeline/logs/run_imaging_pipeline/run_imaging_pipeline_2014-06-27-15-42_PoolWorker-3.log
```

**Comment by acviana** [comment]
Ok, so after thinking about I think we should remove the code you wrote to post-process the log files into a different log file for each process. I'm kind of on the fence about this but I think it simplifies things a little just to leave it as it is and then grep out the information you want. 

Also, you went back and forth between `map` and `async` - which will you use if having a single log file is OK? I don't want anything blocking.

**Comment by walyssonBarbosa** [comment]
Ok.

`map_async` is used when we use a callback function. I forgot to change it to `map` in the first commit.

**Comment by acviana** [comment]
OK. Now that this is running let's benchmark it. Take say, 16 `c0m` rootnames and pick a machine with >16 cores. Run the pipeline with 2, 4, 8, and 16 cores and see if the performance improves as we expect. Run this in a separate test directory on your own machine and do not write the outputs to the main `wfpc2` area.

Part of this will involve thinking about how to parse the new log files will all the cores in one file. Obviously, this is break your old log file parsing script. So for starters just give me the beginning and end time of the entire process. But, think about how the new log format might affect you work in the future and let me know if you think we made the right decision.

**Comment by walyssonBarbosa** [comment]
I used `05216_jupiter_io` to test the performance of parallelizing the pipeline. It has 16 `c0m.fits` files.

I ran it on science4, these are the results:

| Cores | Start | End | Time | % change | t change |
| --- | --- | --- | --- | --- | --- |
| 2 | 16:01:06 | 16:21:28 | 20min22s | - | - |
| 4 | 16:43:17 | 16:51:28 | 8min11s | 36% | 12.25 min |
| 8 | 16:55:13 | 16:59:50 | 4min37s | 57% | 3.5 min |
| 16 | 10:38:41 | 10:41:54 | 3min13s | 86% | 1.5 min |

**Comment by walyssonBarbosa** [comment]
I ran the pipeline with 16 cores. It took 3 minutes and 13 seconds to run, it's a good estimate for how long each `c0m.fits` file will take to process.

**Comment by walyssonBarbosa** [comment]
Are will still going to work on this ticket or we can close it?

**Comment by acviana** [comment]
Can you spot the bottleneck here? Based on the information you gathered on science4 can you guess what might be causing the bottleneck?

**Comment by walyssonBarbosa** [comment]
Could you explain your question a little bit more? I think I didn't understand what you meant.

**Comment by acviana** [comment]
So, as you double the number of processors the processing time should decrease by half - up to a point. At that point the process is no longer "CPU limited" and is limited by either memory or IO (I'm over simplifying a bit). Here I made a chart:

![image](https://cloud.githubusercontent.com/assets/1630700/3498432/457b6350-05f5-11e4-9542-d8c0ee13552a.png)

The blue line is your data, the red line shows the exponential decay curve where the time decreases by a factor of 2 every time you double the number of cores.

So, throwing more and more cores and the problem eventually hits a wall. What I'm really asking is where is this point, why, and what, if anything, should we do about it?

**Comment by walyssonBarbosa** [comment]
I think that to do this I would have to calculate the mean and standard variations for each scenario (times are in seconds):

| cores | cr_avg | cr_std | dr_avg | dr_std | png_avg | png_std | total_avg | total_std |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2 | 11.81 | 1.40 | 40.93 | 2.08 | 99.25 | 4.41 | 151.81 | 4.57 |
| 4 | 8.56 | 0.70 | 34.12 | 1.27 | 77.20 | 4.30 | 119.81 | 4.40 |
| 8 | 9.25 | 0.43 | 39.19 | 1.94 | 83.94 | 5.05 | 132.53 | 5.36 |
| 16 | 11.44 | 2.15 | 73.35 | 5.10 | 95.87 | 7.65 | 180.37 | 10.41 |

I will complete this table. I hope it helps me understand better the process.

**Comment by walyssonBarbosa** [comment]
So far we can suppose that the more the number of cores used the more IO operations will be handled at the same time. In our last test, we used 16 cores, each core processing one `c0m.fits` file. Each `PoolWorker` is trying to write a file to the disk almost at the same time, this generates a queue larger than the ones generated in tests with 2, 4 and 8 cores.

Observing the times in tests with 4 and 8 cores we can see a slightly increase of time from 4 to 8, that meaning that when using 8 cores it will be executed more IO operations at the same time than with 4 cores.

I will finish filling the table with 2 cores results to get a final idea of what is happening.

**Comment by walyssonBarbosa** [comment]
We can see that using 4 cores to process 16 files is the best way of using CPU and IO resources.

**Comment by acviana** [comment]
Well "best" is subjective. I think what you meant is that 4 cores is the most _efficient_. But, just throwing all the cores at the pipeline would still be the fastest, though the gains are increasingly marginal due to the IO bottleneck. 

When we finally get to the point that we're running the pipeline over the ACS/WFC3 images later these number suggest to me that we should run this over as many cores as we can _distributed across as many machines as we can_. I this we I think we can beat the IO bottleneck as best we can.

**Comment by acviana** [comment]
I think we can close this now.
